
// This file has been generated by the GUI designer. Do not modify.
namespace AplikacijaTaxy
{
	public partial class WindowUnosVozila
	{
		private global::Gtk.HBox hbox1;

		private global::Gtk.VBox vbox1;

		private global::Gtk.Label LabelMarka;

		private global::Gtk.Label label2;

		private global::Gtk.Label label3;

		private global::Gtk.Label LabelRegistracija1;

		private global::Gtk.Label LabelVrsta;

		private global::Gtk.VBox vbox2;

		private global::Gtk.Entry UnosMarke;

		private global::Gtk.Entry LabelModel;

		private global::Gtk.SpinButton unosGodineAuta;

		private global::Gtk.Entry LabelRegistracija;

		private global::Gtk.ComboBox combobox1;

		private global::Gtk.VBox vbox3;

		private global::Gtk.Button button1;

		private global::Gtk.Button button2;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget AplikacijaTaxy.WindowUnosVozila
			this.Name = "AplikacijaTaxy.WindowUnosVozila";
			this.Title = global::Mono.Unix.Catalog.GetString("UNOS VOZILA");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			this.Modal = true;
			this.BorderWidth = ((uint)(10));
			// Container child AplikacijaTaxy.WindowUnosVozila.Gtk.Container+ContainerChild
			this.hbox1 = new global::Gtk.HBox();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.vbox1 = new global::Gtk.VBox();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.LabelMarka = new global::Gtk.Label();
			this.LabelMarka.WidthRequest = 100;
			this.LabelMarka.HeightRequest = 50;
			this.LabelMarka.Name = "LabelMarka";
			this.LabelMarka.LabelProp = global::Mono.Unix.Catalog.GetString("MARKA");
			this.vbox1.Add(this.LabelMarka);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.LabelMarka]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.label2 = new global::Gtk.Label();
			this.label2.HeightRequest = 50;
			this.label2.Name = "label2";
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString("MODEL");
			this.vbox1.Add(this.label2);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.label2]));
			w2.Position = 1;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.label3 = new global::Gtk.Label();
			this.label3.WidthRequest = 0;
			this.label3.HeightRequest = 50;
			this.label3.Name = "label3";
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString("GODIŠTE");
			this.vbox1.Add(this.label3);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.label3]));
			w3.Position = 2;
			w3.Expand = false;
			w3.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.LabelRegistracija1 = new global::Gtk.Label();
			this.LabelRegistracija1.HeightRequest = 50;
			this.LabelRegistracija1.Name = "LabelRegistracija1";
			this.LabelRegistracija1.LabelProp = global::Mono.Unix.Catalog.GetString("REGISTRACIJA");
			this.vbox1.Add(this.LabelRegistracija1);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.LabelRegistracija1]));
			w4.Position = 3;
			w4.Expand = false;
			w4.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.LabelVrsta = new global::Gtk.Label();
			this.LabelVrsta.HeightRequest = 50;
			this.LabelVrsta.Name = "LabelVrsta";
			this.LabelVrsta.LabelProp = global::Mono.Unix.Catalog.GetString("VRSTA");
			this.vbox1.Add(this.LabelVrsta);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.LabelVrsta]));
			w5.Position = 4;
			w5.Expand = false;
			w5.Fill = false;
			this.hbox1.Add(this.vbox1);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.vbox1]));
			w6.Position = 0;
			w6.Expand = false;
			w6.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.vbox2 = new global::Gtk.VBox();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.UnosMarke = new global::Gtk.Entry();
			this.UnosMarke.WidthRequest = 200;
			this.UnosMarke.HeightRequest = 50;
			this.UnosMarke.CanFocus = true;
			this.UnosMarke.Name = "UnosMarke";
			this.UnosMarke.IsEditable = true;
			this.UnosMarke.InvisibleChar = '●';
			this.vbox2.Add(this.UnosMarke);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.UnosMarke]));
			w7.Position = 0;
			w7.Expand = false;
			w7.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.LabelModel = new global::Gtk.Entry();
			this.LabelModel.HeightRequest = 50;
			this.LabelModel.CanFocus = true;
			this.LabelModel.Name = "LabelModel";
			this.LabelModel.IsEditable = true;
			this.LabelModel.InvisibleChar = '●';
			this.vbox2.Add(this.LabelModel);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.LabelModel]));
			w8.Position = 1;
			w8.Expand = false;
			w8.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.unosGodineAuta = new global::Gtk.SpinButton(2000D, 2017D, 1D);
			this.unosGodineAuta.HeightRequest = 50;
			this.unosGodineAuta.CanFocus = true;
			this.unosGodineAuta.Name = "unosGodineAuta";
			this.unosGodineAuta.Adjustment.PageIncrement = 10D;
			this.unosGodineAuta.ClimbRate = 1D;
			this.unosGodineAuta.Numeric = true;
			this.unosGodineAuta.SnapToTicks = true;
			this.unosGodineAuta.Value = 2000D;
			this.vbox2.Add(this.unosGodineAuta);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.unosGodineAuta]));
			w9.Position = 2;
			w9.Expand = false;
			w9.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.LabelRegistracija = new global::Gtk.Entry();
			this.LabelRegistracija.HeightRequest = 50;
			this.LabelRegistracija.CanFocus = true;
			this.LabelRegistracija.Name = "LabelRegistracija";
			this.LabelRegistracija.IsEditable = true;
			this.LabelRegistracija.InvisibleChar = '●';
			this.vbox2.Add(this.LabelRegistracija);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.LabelRegistracija]));
			w10.Position = 3;
			w10.Expand = false;
			w10.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.combobox1 = global::Gtk.ComboBox.NewText();
			this.combobox1.AppendText(global::Mono.Unix.Catalog.GetString("Auto"));
			this.combobox1.AppendText(global::Mono.Unix.Catalog.GetString("Kombi"));
			this.combobox1.WidthRequest = 0;
			this.combobox1.HeightRequest = 50;
			this.combobox1.Name = "combobox1";
			this.combobox1.Active = 0;
			this.vbox2.Add(this.combobox1);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.combobox1]));
			w11.Position = 4;
			w11.Expand = false;
			w11.Fill = false;
			this.hbox1.Add(this.vbox2);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.vbox2]));
			w12.Position = 1;
			w12.Expand = false;
			w12.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.vbox3 = new global::Gtk.VBox();
			this.vbox3.Name = "vbox3";
			this.vbox3.Spacing = 6;
			// Container child vbox3.Gtk.Box+BoxChild
			this.button1 = new global::Gtk.Button();
			this.button1.WidthRequest = 150;
			this.button1.HeightRequest = 80;
			this.button1.CanFocus = true;
			this.button1.Name = "button1";
			this.button1.UseUnderline = true;
			this.button1.Label = global::Mono.Unix.Catalog.GetString("SPREMI");
			global::Gtk.Image w13 = new global::Gtk.Image();
			w13.Pixbuf = global::Stetic.IconLoader.LoadIcon(this, "gtk-apply", global::Gtk.IconSize.Menu);
			this.button1.Image = w13;
			this.vbox3.Add(this.button1);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.button1]));
			w14.Position = 0;
			w14.Expand = false;
			w14.Fill = false;
			w14.Padding = ((uint)(30));
			// Container child vbox3.Gtk.Box+BoxChild
			this.button2 = new global::Gtk.Button();
			this.button2.WidthRequest = 150;
			this.button2.HeightRequest = 80;
			this.button2.CanFocus = true;
			this.button2.Name = "button2";
			this.button2.UseUnderline = true;
			this.button2.Label = global::Mono.Unix.Catalog.GetString("ODUSTANI");
			global::Gtk.Image w15 = new global::Gtk.Image();
			w15.Pixbuf = global::Stetic.IconLoader.LoadIcon(this, "gtk-cancel", global::Gtk.IconSize.Menu);
			this.button2.Image = w15;
			this.vbox3.Add(this.button2);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.button2]));
			w16.Position = 1;
			w16.Expand = false;
			w16.Fill = false;
			this.hbox1.Add(this.vbox3);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.vbox3]));
			w17.Position = 2;
			w17.Expand = false;
			w17.Fill = false;
			this.Add(this.hbox1);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 482;
			this.DefaultHeight = 294;
			this.Show();
			this.button1.Clicked += new global::System.EventHandler(this.SpremiVozilo);
			this.button2.Clicked += new global::System.EventHandler(this.OdustaniOdUnosa);
		}
	}
}
