
// This file has been generated by the GUI designer. Do not modify.
namespace AplikacijaTaxy
{
	public partial class WindowUnosVozaca
	{
		private global::Gtk.HBox hbox1;

		private global::Gtk.VBox vbox1;

		private global::Gtk.Label labelIME;

		private global::Gtk.Label labelPREZIME;

		private global::Gtk.Label labelOIB;

		private global::Gtk.Label labelIBAN;

		private global::Gtk.Label labelKONTAKT;

		private global::Gtk.Label label_ADRESA;

		private global::Gtk.Label label_PLACA;

		private global::Gtk.Label label_VOZILO;

		private global::Gtk.VBox vbox2;

		private global::Gtk.Entry entry_IME;

		private global::Gtk.Entry entry_PREZIME;

		private global::Gtk.Entry entryOIB;

		private global::Gtk.Entry entry_IBAN;

		private global::Gtk.HBox hbox2;

		private global::Gtk.Entry entry_KONTAKT;

		private global::Gtk.Entry entry_ADRESA;

		private global::Gtk.SpinButton spinbutton_PLACA;

		private global::Gtk.ComboBox combobox_VOZILO;

		private global::Gtk.VBox vbox3;

		private global::Gtk.Fixed fixed1;

		private global::Gtk.Button button_SPREMI;

		private global::Gtk.Button button_ODUSTANI;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget AplikacijaTaxy.WindowUnosVozaca
			this.Name = "AplikacijaTaxy.WindowUnosVozaca";
			this.Title = global::Mono.Unix.Catalog.GetString("UNOS VOZACA");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			this.Modal = true;
			this.BorderWidth = ((uint)(10));
			// Container child AplikacijaTaxy.WindowUnosVozaca.Gtk.Container+ContainerChild
			this.hbox1 = new global::Gtk.HBox();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.vbox1 = new global::Gtk.VBox();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.labelIME = new global::Gtk.Label();
			this.labelIME.WidthRequest = 100;
			this.labelIME.HeightRequest = 50;
			this.labelIME.Name = "labelIME";
			this.labelIME.LabelProp = global::Mono.Unix.Catalog.GetString("IME");
			this.vbox1.Add(this.labelIME);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.labelIME]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.labelPREZIME = new global::Gtk.Label();
			this.labelPREZIME.HeightRequest = 50;
			this.labelPREZIME.Name = "labelPREZIME";
			this.labelPREZIME.LabelProp = global::Mono.Unix.Catalog.GetString("PREZIME");
			this.vbox1.Add(this.labelPREZIME);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.labelPREZIME]));
			w2.Position = 1;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.labelOIB = new global::Gtk.Label();
			this.labelOIB.HeightRequest = 50;
			this.labelOIB.Name = "labelOIB";
			this.labelOIB.LabelProp = global::Mono.Unix.Catalog.GetString("OIB");
			this.vbox1.Add(this.labelOIB);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.labelOIB]));
			w3.Position = 2;
			w3.Expand = false;
			w3.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.labelIBAN = new global::Gtk.Label();
			this.labelIBAN.HeightRequest = 50;
			this.labelIBAN.Name = "labelIBAN";
			this.labelIBAN.LabelProp = global::Mono.Unix.Catalog.GetString("IBAN");
			this.vbox1.Add(this.labelIBAN);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.labelIBAN]));
			w4.Position = 3;
			w4.Expand = false;
			w4.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.labelKONTAKT = new global::Gtk.Label();
			this.labelKONTAKT.HeightRequest = 50;
			this.labelKONTAKT.Name = "labelKONTAKT";
			this.labelKONTAKT.LabelProp = global::Mono.Unix.Catalog.GetString("BR.MOBITELA");
			this.vbox1.Add(this.labelKONTAKT);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.labelKONTAKT]));
			w5.Position = 4;
			w5.Expand = false;
			w5.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.label_ADRESA = new global::Gtk.Label();
			this.label_ADRESA.HeightRequest = 50;
			this.label_ADRESA.Name = "label_ADRESA";
			this.label_ADRESA.LabelProp = global::Mono.Unix.Catalog.GetString("ADRESA");
			this.vbox1.Add(this.label_ADRESA);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.label_ADRESA]));
			w6.Position = 5;
			w6.Expand = false;
			w6.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.label_PLACA = new global::Gtk.Label();
			this.label_PLACA.HeightRequest = 50;
			this.label_PLACA.Name = "label_PLACA";
			this.label_PLACA.LabelProp = global::Mono.Unix.Catalog.GetString("PLAĆA");
			this.vbox1.Add(this.label_PLACA);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.label_PLACA]));
			w7.Position = 6;
			w7.Expand = false;
			w7.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.label_VOZILO = new global::Gtk.Label();
			this.label_VOZILO.HeightRequest = 50;
			this.label_VOZILO.Name = "label_VOZILO";
			this.label_VOZILO.LabelProp = global::Mono.Unix.Catalog.GetString("VOZILO");
			this.vbox1.Add(this.label_VOZILO);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.label_VOZILO]));
			w8.Position = 7;
			w8.Expand = false;
			w8.Fill = false;
			this.hbox1.Add(this.vbox1);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.vbox1]));
			w9.Position = 0;
			w9.Expand = false;
			w9.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.vbox2 = new global::Gtk.VBox();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.entry_IME = new global::Gtk.Entry();
			this.entry_IME.WidthRequest = 200;
			this.entry_IME.HeightRequest = 50;
			this.entry_IME.CanFocus = true;
			this.entry_IME.Name = "entry_IME";
			this.entry_IME.IsEditable = true;
			this.entry_IME.InvisibleChar = '●';
			this.vbox2.Add(this.entry_IME);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.entry_IME]));
			w10.Position = 0;
			w10.Expand = false;
			w10.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.entry_PREZIME = new global::Gtk.Entry();
			this.entry_PREZIME.HeightRequest = 50;
			this.entry_PREZIME.CanFocus = true;
			this.entry_PREZIME.Name = "entry_PREZIME";
			this.entry_PREZIME.IsEditable = true;
			this.entry_PREZIME.InvisibleChar = '●';
			this.vbox2.Add(this.entry_PREZIME);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.entry_PREZIME]));
			w11.Position = 1;
			w11.Expand = false;
			w11.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.entryOIB = new global::Gtk.Entry();
			this.entryOIB.HeightRequest = 50;
			this.entryOIB.CanFocus = true;
			this.entryOIB.Name = "entryOIB";
			this.entryOIB.IsEditable = true;
			this.entryOIB.InvisibleChar = '●';
			this.vbox2.Add(this.entryOIB);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.entryOIB]));
			w12.Position = 2;
			w12.Expand = false;
			w12.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.entry_IBAN = new global::Gtk.Entry();
			this.entry_IBAN.HeightRequest = 50;
			this.entry_IBAN.CanFocus = true;
			this.entry_IBAN.Name = "entry_IBAN";
			this.entry_IBAN.IsEditable = true;
			this.entry_IBAN.InvisibleChar = '●';
			this.vbox2.Add(this.entry_IBAN);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.entry_IBAN]));
			w13.Position = 3;
			w13.Expand = false;
			w13.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox2 = new global::Gtk.HBox();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.entry_KONTAKT = new global::Gtk.Entry();
			this.entry_KONTAKT.HeightRequest = 50;
			this.entry_KONTAKT.CanFocus = true;
			this.entry_KONTAKT.Name = "entry_KONTAKT";
			this.entry_KONTAKT.IsEditable = true;
			this.entry_KONTAKT.InvisibleChar = '●';
			this.hbox2.Add(this.entry_KONTAKT);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.entry_KONTAKT]));
			w14.Position = 0;
			this.vbox2.Add(this.hbox2);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.hbox2]));
			w15.Position = 4;
			w15.Expand = false;
			w15.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.entry_ADRESA = new global::Gtk.Entry();
			this.entry_ADRESA.HeightRequest = 50;
			this.entry_ADRESA.CanFocus = true;
			this.entry_ADRESA.Name = "entry_ADRESA";
			this.entry_ADRESA.IsEditable = true;
			this.entry_ADRESA.InvisibleChar = '●';
			this.vbox2.Add(this.entry_ADRESA);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.entry_ADRESA]));
			w16.Position = 5;
			w16.Expand = false;
			w16.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.spinbutton_PLACA = new global::Gtk.SpinButton(3000D, 20000D, 100D);
			this.spinbutton_PLACA.HeightRequest = 50;
			this.spinbutton_PLACA.CanFocus = true;
			this.spinbutton_PLACA.Name = "spinbutton_PLACA";
			this.spinbutton_PLACA.Adjustment.PageIncrement = 10D;
			this.spinbutton_PLACA.ClimbRate = 1D;
			this.spinbutton_PLACA.Numeric = true;
			this.spinbutton_PLACA.SnapToTicks = true;
			this.spinbutton_PLACA.Value = 3000D;
			this.vbox2.Add(this.spinbutton_PLACA);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.spinbutton_PLACA]));
			w17.Position = 6;
			w17.Expand = false;
			w17.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.combobox_VOZILO = global::Gtk.ComboBox.NewText();
			this.combobox_VOZILO.HeightRequest = 50;
			this.combobox_VOZILO.Name = "combobox_VOZILO";
			this.vbox2.Add(this.combobox_VOZILO);
			global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.combobox_VOZILO]));
			w18.Position = 7;
			w18.Expand = false;
			w18.Fill = false;
			this.hbox1.Add(this.vbox2);
			global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.vbox2]));
			w19.Position = 1;
			w19.Expand = false;
			w19.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.vbox3 = new global::Gtk.VBox();
			this.vbox3.Name = "vbox3";
			this.vbox3.Spacing = 6;
			// Container child vbox3.Gtk.Box+BoxChild
			this.fixed1 = new global::Gtk.Fixed();
			this.fixed1.HeightRequest = 100;
			this.fixed1.Name = "fixed1";
			this.fixed1.HasWindow = false;
			this.vbox3.Add(this.fixed1);
			global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.fixed1]));
			w20.Position = 0;
			w20.Expand = false;
			w20.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.button_SPREMI = new global::Gtk.Button();
			this.button_SPREMI.WidthRequest = 150;
			this.button_SPREMI.HeightRequest = 80;
			this.button_SPREMI.CanFocus = true;
			this.button_SPREMI.Name = "button_SPREMI";
			this.button_SPREMI.UseUnderline = true;
			this.button_SPREMI.Label = global::Mono.Unix.Catalog.GetString("SPREMI");
			global::Gtk.Image w21 = new global::Gtk.Image();
			w21.Pixbuf = global::Stetic.IconLoader.LoadIcon(this, "gtk-apply", global::Gtk.IconSize.Menu);
			this.button_SPREMI.Image = w21;
			this.vbox3.Add(this.button_SPREMI);
			global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.button_SPREMI]));
			w22.Position = 1;
			w22.Expand = false;
			w22.Fill = false;
			w22.Padding = ((uint)(20));
			// Container child vbox3.Gtk.Box+BoxChild
			this.button_ODUSTANI = new global::Gtk.Button();
			this.button_ODUSTANI.HeightRequest = 80;
			this.button_ODUSTANI.CanFocus = true;
			this.button_ODUSTANI.Name = "button_ODUSTANI";
			this.button_ODUSTANI.UseUnderline = true;
			this.button_ODUSTANI.Label = global::Mono.Unix.Catalog.GetString("ODUSTANI");
			global::Gtk.Image w23 = new global::Gtk.Image();
			w23.Pixbuf = global::Stetic.IconLoader.LoadIcon(this, "gtk-cancel", global::Gtk.IconSize.Menu);
			this.button_ODUSTANI.Image = w23;
			this.vbox3.Add(this.button_ODUSTANI);
			global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.button_ODUSTANI]));
			w24.Position = 2;
			w24.Expand = false;
			w24.Fill = false;
			this.hbox1.Add(this.vbox3);
			global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.vbox3]));
			w25.Position = 2;
			w25.Expand = false;
			w25.Fill = false;
			w25.Padding = ((uint)(10));
			this.Add(this.hbox1);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 502;
			this.DefaultHeight = 469;
			this.Show();
			this.button_SPREMI.Clicked += new global::System.EventHandler(this.spremiVozaca);
			this.button_ODUSTANI.Clicked += new global::System.EventHandler(this.On_button_odustani);
		}
	}
}
